### PR TITLE
Add missing pid spec argument to destroy method

### PR DESCRIPTION
**Pull request by lrascao**
It was missing these, pid type for the queue argument got introduced in #4

### CODE REVIEW

**Comment by jlouis** [comment]
Looking good, going in.

**Comment by lrascao** [comment]
Cool, thanks, could i bother you with a minor version bump please?

**Comment by jlouis** [comment]
Ah, that is a good idea! I'll do that.

**Comment by jlouis** [comment]
Tag `2.5.1` and tag `v2.5.1` pushed with the changes.

**Comment by lrascao** [comment]
:thumbsup:

**Pull request merged**
